### ISSUE TITLE
Poor Commit Authorship

### ISSUE THREAD

**Issue by baalajimaestro** [LineageOS/android_device_xiaomi_violet#1]
The commits on this repo have been seemingly amended authorship to give authorship to the maintainer, leaving behind the actual contributor (@GuaiYiHu). This is seen as a sheer violation of the LineageOS Code of Conduct. You can see commits from (https://github.com/guaiyihu/android_device_xiaomi_violet) just incase  you feel i was wrong.

Hoping the real contributor gets the credits back soon!

Thanks,
baalajimaestro

**Comment by Dyneteve** [comment]
+1

**Comment by venuxvg** [comment]
@baalajimaestro anyway they just ignore this issue like they did earlier on gitlab issues section.

**Comment by baalajimaestro** [comment]
Commit at: https://github.com/LineageOS/android_device_xiaomi_violet/commit/87422f95d45bd6a820460457011d99bc1aa58e17

and 

https://github.com/GuaiYiHu/android_device_xiaomi_violet/commit/88c33de533b0fa9483f19f771f8f9773c35ec843 
squashed with
https://github.com/GuaiYiHu/android_device_xiaomi_violet/commit/707fa1d2b2511c7a3a4f46c6d6a8ad0d082b0292

looks exactly same, and as expected atman(the violet maintainer) has committed not earlier, he has committed 2 days later.

We clearly can find this as a deliberate kang and its demeaning the whole opensource community.

CC: @Rashed97 @luk1337

**Comment by baalajimaestro** [comment]
https://github.com/LineageOS/android_device_xiaomi_violet/commit/2b6f7bbf9cdb612dd48e2eed6eba393e55d651c2

and 

https://github.com/GuaiYiHu/android_device_xiaomi_violet/commit/5747dd3ddc3f730341bc48ba8524830f34e1129c

is another example

**Comment by mikeNG** [comment]
This is not how you engage directors. If you want to engage in a conversation with the directors you email directors@lineageos.org. And you know this.
